### ISSUE TITLE
Fix Swerve

### ISSUE THREAD

**Issue by morgenes** [Team3229/Hawktimus23-24#3]
PID tuning to make sure we aren't drawing too much power.

**Comment by Xolverr** [comment]
Progress from today, added commit to new branch for this issue

**Comment by Xolverr** [comment]
## DevLog | 10/4/2024
- Began tuning PD for swerve module angles
> Still need finalized. Current constants are
> ```
> kP = 0.5
> kD = 0.0035
> ```

### Next Steps
- Finalize PD for module angles
- Start tuning drive PD
- Test driving and cosine scale

**Comment by morgenes** [comment]
Very nice work Nathan! This is a great update. Thanks for the update!

**Comment by morgenes** [comment]
Hey Nathan, I was reviewing the code and noted that you've changed to having your commands in your Subsystems directly.  That doesn't seem to be the pattern I see in the examples provided in the WPILib or in other people, who keep their Commands in a separate directory, each command in a separate class file.  Is there a reason you went with having them be inner classes on your subsystem class?

**Comment by morgenes** [comment]
Ok, I think I see now, you are doing like others and having commands in the subsystem for what it does, what I don't see is the commands that coordinates multiple subsystems together like telling it to work together to pick up a note.  I'm sure you can show it to me.

**Comment by morgenes** [comment]
quick note that at least on my mac, you have a Java compilation issue because the 'Drive' subsystem is upper cased, it should be 'drive' not 'Drive'.

**Comment by Xolverr** [comment]
## DevLog 10/11/2024
- Finalized PID Tuning for the Drive Motors.
```
kDriveFreeSpeed = 5.12 m/s
kFF = 1/kDriveFreeSpeed
```

### Next Steps
- Figure out why the swerve module zeroing wasn't working
- Full test with driving on floor

**Comment by Xolverr** [comment]
> - Figure out why the swerve module zeroing wasn't working

Just looked at the code real quick, and I believe I found the issue.
In ```SwerveModule.initializeTurningEncoderPosition()```, the method used to pull the CANcoder's position was 
```m_turningAbsoluteEncoder.getAbsolutePosition()```. We should have been using
```m_turningAbsoluteEncoder.getPosition()```, because this actually applies our zeroing offsets.
Whereas the ```getAbsolutePosition()``` method ignores any zeroing offset applied, which would result in the behavior we saw.

**Comment by Xolverr** [comment]
The fix was pushed to ```3-fixing-swerve```

**Comment by Xolverr** [comment]
## DevLog Pre-Meeting 10/17/24
- FInished fixing our issues with swerve!
> It turns out it wasn't actually our fault, CTRE Phoenix v6 API for CANcoders is broken. Magnet offsets do not persist. Fixed by adding our own manual offset that simply adds to the absolute position reported by the CANcoder.
